allowMergeCommits: true
allowRevertCommits: true
commitsOnly: true

# Any changes should also me made on the commitizen.js
types:
  - feat
  - fix
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - docs
  - chore
