import { createMock } from 'ts-auto-mock';

describe('Random boolean', () => {
  it('should be generated by math random', () => {
    type WithBoolean = {
      propertyName: boolean;
    };

    const spy: jasmine.Spy = spyOn(Math, 'random');

    spy.and.returnValue(0);

    const mock: WithBoolean = createMock<WithBoolean>();

    // because we are mocking the return value of Math.random with 0 the result should be always !0 = true
    expect(mock.propertyName).toBe(true);

    spy.calls.reset();
    spy.and.returnValue(1);

    const mock2: WithBoolean = createMock<WithBoolean>();
    // because we are mocking the return value of Math.random with 1 the result should be always !1 = false
    expect(mock2.propertyName).toBe(false);
  });
});
