import { createMock } from 'ts-auto-mock';

describe('Random number', () => {
  it('should be generated by math random', () => {
    type WithNumber = {
      propertyName: number;
    };

    const spy: jasmine.Spy = spyOn(Math, 'random');

    spy.and.returnValue(1);

    const mock: WithNumber = createMock<WithNumber>();

    // because we are mocking the return value of Math.random with 1 the result should be = 1 * (10000 - -10000) + -10000
    expect(mock.propertyName).toBe(10000);

    spy.calls.reset();
    spy.and.returnValue(10);

    const mock2: WithNumber = createMock<WithNumber>();

    // because we are mocking the return value of Math.random with 10 the result should be = 10 * (10000 - -10000) + -10000
    expect(mock2.propertyName).toBe(190000);
  });
});
