import { createMock } from 'ts-auto-mock';

describe('Random number', () => {
  it('should be generated by math random', () => {
    type WithString = {
      propertyName: number;
    };

    spyOn(Math, 'random').and.returnValue(1);

    const mock: WithString = createMock<WithString>();

    // Math.random() * (10000 - -10000) + -10000
    // because we are mocking the return value of Math.random with 1 the result should be = 1 * (10000 - -10000) + -10000
    expect(mock.propertyName).toBe(10000);
  });
});
