name: "Automerge"
on:
  pull_request:
    paths:
    - "data/**"
    types:
    - labeled
    - opened
  check_suite:
    types:
    - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: "pascalgn/automerge-action@v0.16.3"
      env:
        MERGE_METHOD: "rebase"
        MERGE_LABELS: "ts-auto-mock-automerge"
        UPDATE_METHOD: "rebase"
        GITHUB_TOKEN: "${{ secrets.GITHUBTYPESCRIPTTDD }}"
