name: Definitely Type build

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'data/**'
      - 'ui/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/gallium, lts/fermium]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: run definitely typed build
      run: |
        npm ci
        npm run build
        npm run build:transformer:definitelyTyped
      env:
        CI: true


