name: Develop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
    - name: performance
      run: |
        cd performance
        npm install
        npm start
    - name: performance push changes
      run: |
        git config --global user.name 'uittorio'
        git config --global user.email 'uittorio@users.noreply.github.com'
        git commit -am "Performance report"
        git push


