name: Test

on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.author.name, 'typescripttdd')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install ts auto mock and run test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
  empty-job:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Emopty job
        run: |
          echo "This job will always succeed"


