name: Push commit on master test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'typescripttdd'
          git config --global user.email 'typescripttdd@gmail.com'
          git add report.txt
          git commit am "test auto commit to master"
          git push
