name: Performance

on:
  push:
    branches:
      - test-pull-request

jobs:
  testPullRequest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: performance push changes
      run: |
        git config --global user.name 'typescripttdd'
        git config --global user.email 'typescripttdd@gmail.com'
        date +%s > report.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TYPESCRIPTTDD }}
      with:
        commit-message: Add Performance data
        committer: typescripttdd <typescripttdd@gmail.com>
        author: typescripttdd <typescripttdd@gmail.com>


